#! /usr/bin/env python

Import( 'env' )


###################################################################
## CHECK FOR NEEDED LIBRARIES
###################################################################

conf = Configure(env)
if not conf.CheckLib('exif'):
    print 'Did not find libexif.a or exif.lib, exiting!'
    Exit(1)
env = conf.Finish()


env.subdirs('icons')

obj=env.kobject('program')
obj.target='kphotobook'


###################################################################
## DETERMINE ALL FILES TO COMPILE
###################################################################

import glob
import os
import string

print "searching cpp and ui files in: ."

cppfiles = []
for dir, dirs, files in os.walk("."):
  cppfiles += glob.glob(os.path.join(dir, "*.cpp"))
  
uifiles = []
for dir, dirs, files in os.walk("."):
  uifiles += glob.glob(os.path.join(dir, "*.ui"))
  
# remove all cpp files where a ui files exists for
for uifile in uifiles:
  cppfile = uifile.replace('.ui', '.cpp')
  if cppfile in cppfiles:
    cppfiles.remove(cppfile)
  
matchingfiles = cppfiles + uifiles
matchingfiles.sort()

obj.source = string.join(matchingfiles, "\n")

print obj.source


###################################################################
## DEFINE THE LIBRARIES TOI LINK AGAINST
###################################################################

#obj.cxxflags='-DQT_THREAD_SUPPORT'
obj.libs='kio kdecore kmdi'
#obj.execute()


###################################################################
## INSTALL SOME CONFIG FILES AND THE TIPS FILE
###################################################################

env.KDEinstall( 'KDEDATA', 'kphotobook', 'kphotobookui.rc' )
env.KDEinstall( 'KDEDATA', 'kphotobook', 'tips' )
env.KDEinstall( 'KDEKCFG', '', 'settings/settings.kcfg' )


